---
title: "ch2_exploratory"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/OneDrive-UBC/MSc/12_analysis/rodent-bee-blueberry")
```

Load and clean data

```{r}
#load packages
library(tidyverse) #data manipulation, visualization etc. (dplyr, ggplot2, tidyr)
library(DHARMa) #diagnostic tools for mixed regression models
library(glmmTMB) #fits generalized linear mixed models, including zero-inflated and overdispersed models
library(car) #tools for regression diagnostics and hypothesis tests
library(emmeans)   # for estimated marginal means (predictions)

#read in data
data <- read.csv("06_cleandata/combined_plot_data.csv")

#change character columns to factors
surveys <- data %>%
   mutate(
     site_id = as.factor(site_id),
     round = as.factor(round),
     plot_id = as.factor(plot_id),
     bee_date = as.Date(bee_date),
     bee_season_type = as.factor(bee_season_type),
     area = as.factor(area),
     cover_type = as.factor(cover_type))

#add plot type column and make it a factor
surveys <- surveys %>% 
  mutate(plot_type = if_else(plot_id == "d", "ditch", "field"))
surveys <- surveys %>%
   mutate(
     plot_type = as.factor(plot_type))

#scale continuous predictors
surveys$julian.date_scaled <- as.numeric(scale(surveys$julian.date))
surveys$bare_perc_scaled <- as.numeric(scale(surveys$bare_perc))
surveys$grass_perc_scaled <- as.numeric(scale(surveys$grass_perc))
surveys$forb_perc_scaled <- as.numeric(scale(surveys$forb_perc))
surveys$grass_forb_perc_scaled <- as.numeric(scale(surveys$grass_forb_perc))
surveys$grass_h_scaled <- as.numeric(scale(surveys$grass_h))
surveys$forb_h_scaled <- as.numeric(scale(surveys$forb_h))
surveys$floral_perc_scaled <- as.numeric(scale(surveys$floral_perc))
surveys$grass_forb_floral_perc_scaled <- as.numeric(scale(surveys$grass_forb_floral_perc))
surveys$bombus_floral_perc_scaled <- as.numeric(scale(surveys$bombus_floral_perc))
surveys$flood_perc_scaled <- as.numeric(scale(surveys$flood_perc))
surveys$dry_root_perc_scaled <- as.numeric(scale(surveys$dry_root_perc))
surveys$bryo_perc_scaled <- as.numeric(scale(surveys$bryo_perc))
surveys$bare_flood_dry_bryo_perc_scaled <- as.numeric(scale(surveys$bare_flood_dry_bryo_perc))
surveys$floral_richness_scaled <- as.numeric(scale(surveys$floral_richness))
surveys$bombus_floral_richness_scaled <- as.numeric(scale(surveys$bombus_floral_richness))
surveys$bombus_floral_abun_scaled <- as.numeric(scale(surveys$bombus_floral_abun))
surveys$nest_searching_queens_scaled <- as.numeric(scale(surveys$nest_searching_queens))
surveys$workers_scaled <- as.numeric(scale(surveys$workers))
surveys$forage_vaco_scaled <- as.numeric(scale(surveys$forage_vaco))
surveys$num_burrows_scaled <- as.numeric(scale(surveys$num_burrows))
surveys$num_inactive_burrows_scaled <- as.numeric(scale(surveys$num_inactive_burrows))
surveys$num_active_dm_scaled <- as.numeric(scale(surveys$num_active_dm))
surveys$num_dm_size_scaled <- as.numeric(scale(surveys$num_dm_size))
surveys$num_inactive_dm_scaled <- as.numeric(scale(surveys$num_inactive_dm))
```

Find out when blueberry bloom occurs

```{r}
#load floral data
floral <- read.csv("06_cleandata/floral_clean.csv")

#filter to only blueberry flowers
vaco_flowers <- filter(floral, flower_code == "vaco")

#number of plots where VACO abundance = 5 for each date, across both sampling years
vaco_daily <- vaco_flowers %>%
  mutate(
    date_clean = as.Date(date), 
    #Create the dummy year (using 2024 as the reference)
    dummy_date = as.Date(paste0("2024-", month(date_clean), "-", day(date_clean)))
  ) %>%
  group_by(dummy_date) %>%
  summarise(num_plots_high_vaco = sum(abundance == 5, na.rm = TRUE))

# Check the result
ggplot(vaco_daily, aes(x = dummy_date, y = num_plots_high_vaco)) +
  geom_col(fill = "steelblue") + 
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  scale_x_date(limits = c(as.Date("2024-04-01"), as.Date("2024-07-31")),
    date_breaks = "1 month", 
    date_labels = "%b") + 
  labs(
       x = "Date",
       y = "Number of plots with\nhigh VACO abundance") +
  theme_classic(base_size = 13)

# Filter for days that actually have bars (count > 0)
active_dates <- vaco_daily %>%
  filter(num_plots_high_vaco > 0)

# Get the range
start_date <- min(active_dates$dummy_date) ##April 19
end_date <- max(active_dates$dummy_date) ##May 24
```
