---
title: "ch2_extra"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/OneDrive-UBC/MSc/12_analysis/rodent-bee-blueberry")
```

# Load data

```{r}
#load packages
library(ggplot2) #for plots
library(dplyr) #for working with dataframes
library(tidyr) #for working with datasets
library(lme4) #for mixed effects models
library(ggpubr) #for adding significance asterisks to graph
library(stringr)
library(lubridate)

#read in data
data <- read.csv("06_cleandata/combined_plot_data.csv")
rodent <- read.csv("06_cleandata/rodent_clean.csv")

#change character columns to factors
data <- data %>%
   mutate(
     site_id = as.factor(site_id),
     round = as.factor(round),
     plot_id = as.factor(plot_id),
     bee_date = as.Date(bee_date),
     area = as.factor(area))

#add column for ditch vs field
##in overall data
data <- data %>%
  mutate(field_ditch = case_when(
    str_detect(plot_id, "p1|p2") ~ "field",
    str_detect(plot_id, "d") ~ "ditch",
    TRUE ~ NA_character_
  ))

##in rodent data
rodent <- rodent %>%
  mutate(field_ditch = case_when(
    str_detect(plot_id, "p1|p2") ~ "field",
    str_detect(plot_id, "d") ~ "ditch",
    TRUE ~ NA_character_
  ))
```

# Bumble bee floral info

## Load data

```{r}
bee <- read.csv("06_cleandata/bee_clean.csv")
##add ditch vs field column
bee <- bee %>%
  mutate(field_ditch = case_when(
    str_detect(plot_id, "p1|p2") ~ "field",
    str_detect(plot_id, "d") ~ "ditch",
    TRUE ~ NA_character_
  ))
queens <- bee %>%
  filter(caste == "q", flower_species != "" & !is.na(flower_species))
workers <- bee %>%
  filter(caste == "w", flower_species != "" & !is.na(flower_species))
```

## Flower species used by bees

### Overall

Queens

```{r}
queens %>%
  count(flower_species, name = "count") %>%
  mutate(flower_species = reorder(flower_species, -count)) %>%
  ggplot(aes(flower_species, count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.15, size = 3) +
  theme_classic(base_size = 15) +
  xlab("Floral species") +
  ylab("Queen count") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Workers

```{r}
workers %>%
  count(flower_species, name = "count") %>%
  mutate(flower_species = reorder(flower_species, -count)) %>%
  ggplot(aes(flower_species, count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.15, size = 3) +
  theme_classic(base_size = 15) +
  xlab("Floral species") +
  ylab("Worker count") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

### Separated by plot type (ditch vs field)

Queens

```{r}
queens %>%
  count(flower_species, field_ditch, name = "count") %>%
  mutate(flower_species = reorder(flower_species, -count)) %>%
  ggplot(aes(flower_species, count, fill = field_ditch)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = count), 
            position = position_dodge(width = 0.9),
            vjust = -0.15, 
            size = 3) +
  theme_classic(base_size = 15) +
  xlab("Floral species") +
  ylab("Queen count") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Workers

```{r}
workers %>%
  count(flower_species, field_ditch, name = "count") %>%
  mutate(flower_species = reorder(flower_species, -count)) %>%
  ggplot(aes(flower_species, count, fill = field_ditch)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = count), 
            position = position_dodge(width = 0.9),
            vjust = -0.15, 
            size = 3) +
  theme_classic(base_size = 15) +
  xlab("Floral species") +
  ylab("Workers count") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Look at floral availability at sites

```{r}
#load data
floral <- read.csv("06_cleandata/floral_clean.csv")
##add ditch vs field column
floral <- floral %>%
  mutate(field_ditch = case_when(
    str_detect(plot_id, "p1|p2") ~ "field",
    str_detect(plot_id, "d") ~ "ditch",
    TRUE ~ NA_character_
  ))
```

Plot \# foraging bees in ditch vs field across time

```{r}
#add column for julian date
bee$julian.date <- yday(bee$date)

# Step 1: Filter and summarize data
foraging_summary <- bee %>%
  filter(behaviour == "foraging") %>%
  count(julian.date, field_ditch, name = "n_foraging")

# Step 2: Plot
ggplot(foraging_summary, aes(x = julian.date, y = n_foraging, color = field_ditch)) +
  geom_line(size = 1.2) +
  labs(
    title = "# Bombus Foraging vs. Time",
    x = "Julian Date",
    y = "# Foraging Bombus",
    color = "Plot Type"
  ) +
  theme_classic()
```

Plot floral species

```{r}
species_plot_counts <- floral %>%
  count(flower_species, name = "num_plots") %>%
  arrange(desc(num_plots))

# Step 3: Plot
ggplot(species_plot_counts, aes(x = reorder(flower_species, -num_plots), y = num_plots)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  labs(title = "Number of Plots Observed per Floral Species",
       x = "Floral Species",
       y = "Number of Plots") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
