---
title: "supplementary_materials"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/OneDrive-UBC/MSc/12_analysis/rodent-bee-blueberry")
```

Load data

```{r}
#load package
library(tidyverse)   #data manipulation, visualization etc. (dplyr, ggplot2, tidyr)

#read in data
bee <- read.csv("06_cleandata/bee_clean.csv")
floral <- read.csv("06_cleandata/floral_clean.csv")
rodent <- read.csv("06_cleandata/rodent_cleanv2.csv")
site_info <- read.csv("06_cleandata/site_info_clean.csv")

#filter rodent burrows to only 2024 r1
rodent <- rodent %>%
  filter(round == "2024_r1")
```

Add area names to datasets

```{r}
bee <- bee %>%
  left_join(site_info %>% dplyr::select(site_id, area, cover_type), by = c("site_id"))

floral <- floral %>%
  left_join(site_info %>% dplyr::select(site_id, area, cover_type), by = c("site_id"))

rodent <- rodent %>%
  left_join(site_info %>% dplyr::select(site_id, area, cover_type), by = c("site_id"))
```

Add plot type column to datasets
```{r}
bee <- bee %>%
  mutate(plot_type = if_else(plot_id == "d", "ditch", "field")) %>%
  mutate(plot_type = as.factor(plot_type))

floral <- floral %>%
  mutate(plot_type = if_else(plot_id == "d", "ditch", "field")) %>%
  mutate(plot_type = as.factor(plot_type))
  
rodent <- rodent %>%
  mutate(plot_type = if_else(plot_id == "d", "ditch", "field")) %>%
  mutate(plot_type = as.factor(plot_type))
```

Create bee summary table

```{r}
library(janitor)

bee_summary <- bee %>%
  # treat empty strings as NA
  mutate(
    caste = na_if(caste, ""),
    bee_species = na_if(bee_species, "")
  ) %>%
  group_by(bee_species) %>%
  summarise(
    `Total individuals (count)` = n(),
    `Queens (count)` = sum(caste == "q", na.rm = TRUE),
    `Workers (count)` = sum(caste == "w", na.rm = TRUE),
    `Males (count)` = sum(caste == "m", na.rm = TRUE),
    `Unknown caste (count)` = sum(is.na(caste)),
    .groups = "drop"
  ) %>%
  mutate(
    `Relative frequency` = 
      `Total individuals (count)` / sum(`Total individuals (count)`)
  ) %>%
  arrange(desc(`Total individuals (count)`))  %>%
  mutate(
    bee_species = replace_na(bee_species, "unknown")
  ) %>%
  adorn_totals(
    where = "row", 
    fill = "-",          # What to put in character columns that can't be summed
    na.rm = TRUE, 
    name = "Total"       # The label that goes into your first column (bee_species)
  )
```

Create site-level summary table for bumble bees, rodent burrows, and flowers

```{r}
#bee
site_level_summary_bee <- bee %>%
  mutate(
    cover_type = factor(cover_type, levels = c("grass", "bare")), 
    plot_id = factor(plot_id, levels = c("d", "p1", "p2")),
    bee_species = na_if(bee_species, "")
  ) %>%
  group_by(area, cover_type, site_id, plot_id, plot_type) %>%
  summarise(
    `Bombus individuals (count)` = n(),
    `Bee species richness` = n_distinct(bee_species, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(plot_type)

#rodent
site_level_summary_rodent <- rodent %>%
  mutate(
    cover_type = factor(cover_type, levels = c("grass", "bare")),
    plot_id = factor(plot_id, levels = c("d", "p1", "p2"))
  ) %>%
  group_by(area, cover_type, site_id, plot_id, plot_type) %>%
  summarise(
    `Rodent burrows (count)` = n(),
    .groups = "drop"
  ) %>%
  arrange(plot_type)

#floral
site_level_summary_floral <- floral %>%
  mutate(
    cover_type = factor(cover_type, levels = c("grass", "bare")),
    plot_id = factor(plot_id, levels = c("d", "p1", "p2"))
  ) %>%
  group_by(area, cover_type, site_id, plot_id, plot_type) %>%
  summarise(
    `Average floral abundance (log-scale)` = mean(abundance),
    `Floral species richness` = n(),
    .groups = "drop"
  ) %>%
  arrange(plot_type)
```

Combine into one site-level summary table

```{r}
site_level_summary <- site_level_summary_bee %>%
  left_join(
    site_level_summary_rodent %>%
      dplyr::select(area, site_id, plot_id, cover_type, plot_type, `Rodent burrows (count)`),
    by = c("area", "site_id", "plot_id", "cover_type", "plot_type")
  ) %>% 
  left_join(
    site_level_summary_floral %>%
      dplyr::select(area, site_id, plot_id, cover_type, plot_type, `Average floral abundance (log-scale)`, `Floral species richness`),
    by = c("area", "site_id", "plot_id", "cover_type", "plot_type")
  )
    
```

Reshape table so that columns = site name > plot type > plot id, and rows = metrics and then split table by cover type

```{r}
summary_clean <- site_level_summary %>%
  mutate(
    `Bombus individuals (count)`          = replace_na(`Bombus individuals (count)`, 0),
    `Bee species richness`                 = replace_na(`Bee species richness`, 0),
    `Rodent burrows (count)`               = replace_na(`Rodent burrows (count)`, 0),
    `Average floral abundance (log-scale)` = replace_na(`Average floral abundance (log-scale)`, 0),
    `Floral species richness`              = replace_na(`Floral species richness`, 0))

#filter to only grassy
summary_table_grass <- summary_clean %>%
  filter(cover_type == "grass") %>% 
  dplyr::select(area, site_id, plot_type, plot_id, 
         `Bombus individuals (count)`, `Bee species richness`, 
         `Rodent burrows (count)`, `Average floral abundance (log-scale)`, 
         `Floral species richness`) %>%
  arrange(area, site_id, plot_type, plot_id) # Sorts ditch (d) first, then field (p1, p2)

#filter to only bare
summary_table_bare <- summary_clean %>%
  filter(cover_type == "bare") %>% 
  dplyr::select(area, site_id, plot_type, plot_id, 
         `Bombus individuals (count)`, `Bee species richness`, 
         `Rodent burrows (count)`, `Average floral abundance (log-scale)`, 
         `Floral species richness`) %>%
  arrange(area, site_id, plot_type, plot_id) # Sorts ditch (d) first, then field (p1, p2)

#export as csv
write.csv(summary_table_grass, "07_outputs/summary_table_grassy_sites.csv", row.names = FALSE)
write.csv(summary_table_bare, "07_outputs/summary_table_bare_sites.csv", row.names = FALSE)
```

