---
title: "ch1_extra"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/OneDrive-UBC/MSc/12_analysis/rodent-bee-blueberry")
```

# Load data

```{r}
#load packages
library(tidyverse)
library(ggplot2) #for plots
library(dplyr) #for working with dataframes
library(tidyr) #for working with datasets
library(lme4) #for mixed effects models
library(ggpubr) #for adding significance asterisks to graph

#read in data
data <- read.csv("06_cleandata/combined_plot_data.csv")

#check that variables are in appropriate format
str(data)

#change character columns to factors
data <- data %>%
   mutate(
     site_id = as.factor(site_id),
     round = as.factor(round),
     plot_id = as.factor(plot_id),
     bee_date = as.Date(bee_date),
     area = as.factor(area))

#filter data to only include within field data
data <- data %>%
  filter(plot_id != "d")
```

# Comparing predictors across cover types (grassy vs bare).

## % grass+forb

Overall:

```{r}
ggplot(data, aes(x = cover_type, y = grass_forb_perc)) + 
  geom_boxplot() +
  theme_classic(base_size = 15) +
  xlab("Cover") +
  ylab("% grass + forb") +
  stat_compare_means(
    method = "t.test",        # or "wilcox.test"
    label = "p.format",       # shows formatted p-value
    size = 3.7,
    vjust = 0
  )
```

By area:

```{r}
ggplot(data, aes(x = area, fill = cover_type, y = grass_forb_perc)) + 
  geom_boxplot() +
  theme_classic(base_size = 15) +
  xlab("Area") +
  ylab("% grass + forb") +
  stat_compare_means(
    method = "t.test",        # or "wilcox.test"
    label = "p.format",       # shows formatted p-value
    size = 3.7,
    vjust = 0
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## NSQ

```{r}
ggplot(data, aes(fill=cover_type,x=bee_season_type, y = nest_searching_queens))+ 
  geom_boxplot() +
  theme_classic(base_size = 15)+
  xlab("Season")+
  ylab("NSQ abundance") +
  stat_compare_means(
    aes(group = cover_type),  # group by field.type
    method = "t.test",  # or "wilcox.test" if you're doing a non-parametric test
    label = "p.format",  # Display p-value 
    size = 3.7)  # Adjust this value to make the asterisks larger
```

## Workers

```{r}
ggplot(data, aes(fill=cover_type,x=bee_season_type, y = nest_searching_queens))+ 
  geom_boxplot() +
  theme_classic(base_size = 15)+
  xlab("Season")+
  ylab("NSQ abundance") +
  stat_compare_means(
    aes(group = cover_type),  # group by field.type
    method = "t.test",  # or "wilcox.test" if you're doing a non-parametric test
    label = "p.format",  # Display p-value 
    size = 3.7)  # Adjust this value to make the asterisks larger
```

## Rodent burrows

```{r}
ggplot(data, aes(x=cover_type, y = num_burrows))+ 
  geom_boxplot() +
  theme_classic(base_size = 15)+
  xlab("Cover")+
  ylab("Burrow abundance") +
  stat_compare_means(
    aes(group = cover_type),  # group by field.type
    method = "t.test",  # or "wilcox.test" if you're doing a non-parametric test
    label = "p.format",  # Display p-value 
    size = 3.7)  # Adjust this value to make the asterisks larger
```

## Floral abundance (relevant to bees)

```{r}
ggplot(data, aes(x=cover_type, y = bombus_floral_abun))+ 
  geom_boxplot() + 
  theme_classic(base_size = 15)+ 
  xlab("Cover")+ 
  ylab("Bombus-relevant floral abundance") + 
  stat_compare_means( aes(group = cover_type), # group by field.type
                      method = "t.test", # or "wilcox.test" if you're doing a non-parametric test 
                      label = "p.format", # Display p-value 
                      size = 3.7) # Adjust this value to make the asterisks larger
```

## Bees foraging on vaco

```{r}
ggplot(data, aes(x=cover_type, y = forage_vaco))+ 
  geom_boxplot() +
  theme_classic(base_size = 15)+
  xlab("Cover")+
  ylab("Num foraging on vaco") +
  stat_compare_means(
    aes(group = cover_type),  # group by field.type
    method = "t.test",  # or "wilcox.test" if you're doing a non-parametric test
    label = "p.format",  # Display p-value 
    size = 3.7) # Adjust this value to make the asterisks larger
```

# Rodent burrows

## Inactive vs active

```{r}
rodent <- read.csv("06_cleandata/rodent_clean.csv") 

rodent_powder <- rodent %>%
  filter(powder_active_FINAL != "")

burrow_counts <- rodent_powder %>%
  group_by(site_id, powder_active_FINAL) %>%
  summarise(num_burrows = n(), .groups = "drop")

ggplot(burrow_counts, aes(x=site_id, y = num_burrows, fill = powder_active_FINAL))+ 
  geom_bar(stat = "identity",  position = "dodge") +
  theme_classic(base_size = 15)+
  xlab("Activity")+
  ylab("Num burrows") 

prop_inactive <- rodent_powder %>%
  group_by(site_id) %>%
  summarise(
    total_burrows = n(),
    inactive_burrows = sum(powder_active_FINAL == "n", na.rm = TRUE),
    prop_inactive = inactive_burrows / total_burrows
  )

prop_inactive <- prop_inactive %>%
  mutate(site_id = factor(site_id, levels = site_id[order(total_burrows, decreasing = TRUE)]))

ggplot(prop_inactive, aes(x = site_id, y = prop_inactive)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme_classic(base_size = 15) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("Site Name (ordered by total burrow count)") +
  ylab("Proportion inactive burrows") + 
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "red") + 
  geom_text(aes(label = round(prop_inactive, 2)), 
            vjust = -0.5, 
            size = 4)

weighted_avg_prop_inactive <- sum(prop_inactive$inactive_burrows) / sum(prop_inactive$total_burrows)
weighted_avg_prop_inactive
##0.4928571
```

# Number of individuals observed 

## Bees

```{r}
#load bee data
bee <- read.csv("06_cleandata/bee_clean.csv")
bee <- filter(bee, plot_id != "d")

#number of individuals seen in each caste
queen_num <- count(bee, caste == "q") ##168
worker_num <- count(bee, caste == "w") ##36
male_num <- count(bee, caste == "m") ##9
unknown_num <- count(bee, caste == "") ##108
total_bee <- count(bee) ##321
##put into table
bee_count_summary <- bee %>%
  #change blanks to unknown
  mutate(caste = ifelse(caste == "" , "unknown", caste)) %>%
  # Group by species and caste
  group_by(caste) %>%
  summarise(n = n(), .groups = "drop") %>%
  # Add a total row
  bind_rows(tibble(caste = "overall", n = sum(.$n)))
  
#number of species
#put into a table
bee_species_summary <- bee %>%
  #change blanks to unknown
  mutate(caste = ifelse(caste == "" , "unknown", caste)) %>%
  mutate(bee_species = ifelse(bee_species == "" , "unknown", bee_species)) %>%
  # Group by species and caste
  group_by(bee_species, caste) %>%
  summarise(n = n(), .groups = "drop") %>%
  # Pivot caste levels into columns
  pivot_wider(
    names_from = caste,
    values_from = n,
    values_fill = 0  # fill missing combinations with 0
  ) %>%
  # Add a total count column
  mutate(n_overall = rowSums(across(-bee_species)))

```

## Rodents

```{r}
#load bee data
rodent <- read.csv("06_cleandata/rodent_clean.csv")
rodent <- filter(rodent, plot_id != "d")

#number of individuals
total_rodent <- count(rodent) ##517 across all sites
#average per plot
rodent_plot_summary <- rodent %>%
  # Group by plot and site
  group_by(site_id, plot_id) %>%
  summarise(n = n(), .groups = "drop") %>%
  # Pivot caste levels into columns
  pivot_wider(
    names_from = site_id,
    values_from = n,
    values_fill = 0  # fill missing combinations with 0
  )
```

## Floral species

```{r}
floral <- read.csv("06_cleandata/floral_clean.csv")
floral <- filter(floral, plot_id != "d")

beefloral <- read.csv("06_cleandata/useful_flowers.csv")

floral_bombus <- floral %>%
  filter(flower_species %in% beefloral$flower_species |
           str_detect(flower_species, "brassica_") |
           str_detect(flower_species, "rhododendron_") |
           str_detect(flower_species, "rorippa_") |
           str_detect(flower_species, "rubus_") |
           str_detect(flower_species, "rosa_") |
           str_detect(flower_species, "calystegia_") |
           str_detect(flower_species, "prunus_") |
           str_detect(flower_species, "phacelia_") 
  )

#count number of floral species:
length(unique(floral_bombus$flower_species)) ##31
```
