---
title: "Creating sampling event file"
author: "Robin Glover"
csl: https://www.zotero.org/styles/elsevier-harvard
output: pdf_document
bibliography: 
---
Load packages
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

Creating sample event list
```{r}

#create vector for site names
site_names <- c("bates_57b", "bks_56", "chong_68", "bks_68", "chong_96", "bks_96", "gwb_neaves", "bks_neaves", "avtar_168", "surjit_168", "sandhu_ladnertrunk", "lbf_ladnertrunk")

#create vector for round numbers
round <-c("r1", "r2", "r3")

#create vector for plots
plots <-c("p1", "p2", "d")

#create vector for transects
transect <-c("t1", "t2")

#create vector for sections for veg survey
section <-c("veg-q1e", "veg-q2e", "veg-q3e", "veg-q1m", "veg-q2m", "veg-q3m")

#combine vectors into dataframe 
Robin_samples1 <- site_names %>%
  expand_grid(round, plots, transect, section)

#change round, transect and section vector to only contain those associated with bumble 
#bee net surveys
round <- c("r1", "r2")
transect <- c("full-plot")
section <- c("net")

#add rows to dataframe
Robin_samples2 <- site_names %>%
  expand_grid(round, plots, transect, section) %>% 
  bind_rows(Robin_samples1) 

#change round, transect and section vector to only contain those associated with rodent 
#surveys
round <- c("r1", "r2")
transect <-c("t1", "t2")
section <- c("rod-s1", "rod-s2", "rod-s3", "rod-s4", "rod-s5")

#add rows to dataframe
Robin_samples3 <- site_names %>%
  expand_grid(round, plots, transect, section) %>% 
  bind_rows(Robin_samples2) %>% View()

```

